### PR TITLE
electron-5: Added support for Electron 5

### PR DESCRIPTION
**Pull request by KoenLav**
Electron 5 no longer supports protocol.registerStandardSchemes; it was replaced by protocol.registerSchemesAsPrivileged.

### CODE REVIEW

**Comment by KoenLav** [comment]
@wojtkowiak will you get a chance to take a look at this in the near future (now Electron 5 has been released)?

**Comment by dorian-coygo** [comment]
Is there any update on this (maybe offline conversations?) @KoenLav ?

**Comment by KoenLav** [comment]
@dorian-coygo no updates.

Pinging @wojtkowiak

**Comment by wojtkowiak** [comment]
Hey, sorry for a half a year of silence. I will try to resume working on meteor-desktop within a week. 
It's been a crazy time for me and I am no longer working on a meteor project but I still intend to take care of this package.

**Comment by KoenLav** [comment]
@wojtkowiak have you seen this initiative: https://github.com/Meteor-Community-Packages

Maybe it's a good idea to create a bit more documentation on how to release meteor-desktop as a package on NPM and works towards transferring it over to the Meteor Community Packages organization at some point?

Thanks for all your hard work either way!

**Comment by dorian-coygo** [comment]
Also happy to use GitHub sponsors. If you decide to move away from the package, thank you so much for all your hard work!

**Pull request merged**
