### PR TITLE
Upgrade electron-builder to 19.48.3

### PR DESCRIPTION
**Pull request by KoenLav**
Also updated other packages.

Implemented electron-builder-lib (now contains the utils for building like yarn and getElectronVersion).

Question: how do I 'build' this so I can test out this release myself?

### CODE REVIEW

**Comment by KoenLav** [comment]
Found out how to run and fixed some small bugs.

Currently stuck at: ERROR  electronBuilder:  error while building installer:  Error: Unresolved node modules: connect, server-destroy, etc.

Probably has to do with the createLazyProductionDeps or electron-builder now looking for dependencies somewhere else than before.

**Comment by Jaradacl** [comment]
Any progress on this?

**Comment by KoenLav** [comment]
@wojtkowiak any pointers would be greatly appreciated!

**Comment by wojtkowiak** [comment]
Hey, big thanks for this PR. I just picked it up. The node_modules are packed into app.asar, and now electron-builder is looking for them. Not sure at the moment what needs to be done.
I will try to release and update by the end of next week.

**Comment by KoenLav** [comment]
@wojtkowiak any further info on what would need to be done to resolve the issue?

**Comment by wojtkowiak** [comment]
@KoenLav once again, thanks for this. I needed to make some changes in `electron-builder` .
https://github.com/electron-userland/electron-builder/pull/2556/files

`electron-builder` update is now released in `0.12.0`, please check it out.

**Comment by KoenLav** [comment]
@wojtkowiak are there any issues to be expected with 0.12 (other than the config files differing)?

I'll check it out right away.

**Comment by wojtkowiak** [comment]
Well I've checked it with all my projects, building for Windows / Mac (including building Window on Mac etc) and so far it looks good. But electron-builder was not updated for quite a long time so I am expecting people running into possible problems.

**Pull request closed without merging**
